spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/github_ems
        username: root
        password: root
        type: org.apache.commons.dbcp.BasicDataSource